### ISSUE TITLE
Essentials Real-time sync and Custom Model Data support

### ISSUE THREAD

**Issue by FrancescoJacovo** [Banarnia-Services/FancyHomes#2]
I'll write here what i answered u before knowing that the issue was closed:

Like the origin-realms server: you have a homes gui with 54 size and in every slot u see a lock "locked" and "unlocked" to represent the homes that the specific player have, can set and cannot set because doesn't have a specific rank. They show this distinction with custom-model-data (so minecraft custom textured) and lores!

Cool for the import but i was talking about a sync with essentials in real-time

**Comment by MikeNipkow** [comment]
That'd be more like an essentials addon I guess.

I suppose you wouldn't need the /sethome /home and /delhome commands, as they already come from essentials. If I am not mistaken you only need a gui that hooks into essentials, right?

I don't know the origin-realms implementation, maybe you can provide some screenshots so that I get the idea.

Can't promise you to implement it though as it barely has something to do with this general plugin.

**Comment by FrancescoJacovo** [comment]
![image](https://github.com/Banarnia-Services/FancyHomes/assets/8696665/b743120d-c1fb-42b0-8a6c-ef5baf17daf4)
![image](https://github.com/Banarnia-Services/FancyHomes/assets/8696665/ba7ed2a0-6826-4b1e-ae7b-3c576e3a7916)
![image](https://github.com/Banarnia-Services/FancyHomes/assets/8696665/4d934e3f-52fa-458d-9608-7572f64ec4ea)
